### ISSUE TITLE
vue.js中集成ueditor?

### ISSUE THREAD

**Issue by JiayiLi** [JiayiLi/TristaLee-vue-blog#2]
步骤一：在 是 src/assets/ 文件内新建 ueditor 文件夹并引入 uedior相关插件代码

步骤二：在 static文件夹中也同样引入uedior相关插件代码

步骤三：在 main.js 中引入  
```javascript
import './assets/utf8-php/ueditor.config.js'
import './assets/utf8-php/ueditor.all.min.js'
import './assets/utf8-php/lang/zh-cn/zh-cn.js'
import './assets/utf8-php/ueditor.parse.min.js'
```
 
步骤四：修改配置 uedior 配置文件相关根目录： src/assets/utf8-php/ueditor.config.js 中将
window.UEDITOR_HOME_URL = "/static/utf8-php/";

引入成功。
然后就是在目标页面 进行初始化 ,具体代码详见 components 中的 addnew 页面。

**Comment by YangYuChan** [comment]
就是按照你这步骤一步一步来的，但是现在报了Uncaught TypeError: Cannot read property 'offsetWidth' of null 请问是什么原因呢
