### ISSUE TITLE
咨询ueditor的问题

### ISSUE THREAD

**Issue by cody1991** [JiayiLi/TristaLee-vue-blog#9]
最近也在整合 element 和 ueditor  的，按照你知乎的回答，我跟着设置了下，也下载了你这个库，但是发现有两个问题

一个是使用 ueditor 的时候， webpack 应该是默认生成的代码是 'use strict' 的，所以会有下面的报错：

```
ueditor.all.min.js?b8ab:18 Uncaught TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at HTMLDocument.d (eval at <anonymous>
```

第二个我看到你的demo，也是会这样报错：

```
ueditor.all.min.js?b8ab:9 后台配置项返回格式出错，上传功能将不能正常使用！
```

特别是第二个问题，应该怎么解决呢

**Comment by JiayiLi** [comment]
知乎上的回答只是可以让插件正常显示，后面还有一些坑，在我的这个项目 已关闭的issue 都有解决。

你的两个问题都已解决 

问题1:    [报错Uncaught TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them](https://github.com/JiayiLi/TristaLee-vue-blog/issues/1)


问题2：后台配置项返回格式出错，上传功能将不能正常使用，这个主要就是后台配置有问题，上传图片这些功能不能使用，所以报错。不知道你怎么看到我的demo （；￣ェ￣），难道 下了本地跑了吗？可是问题是 我的php后台环境在我本地起的apache 服务上起来，这个项目里的php代码 只是个展示。所以并不是真的我的后台。(´･_･`)
[ueditor 上传图片路径配置](https://github.com/JiayiLi/TristaLee-vue-blog/issues/7)

**Comment by cody1991** [comment]
非常感谢。。这么快回复了

中午没睡 眼瞎了 看的时候 1 open 0 close.. 以为就一个不关我事的 issue 。。

然后就开了这个 issue 

非常感谢！我先看看去哈

**Comment by JiayiLi** [comment]
客气了(￣▽￣) 
共同学习交流。

有问题再评论哈～
issue 先关了 (´･_･`)
